/* The one piece of this site that is not a static file.
   ------------------------------------------------------------------
   It answers a single question — how many people are reading the
   portfolio right now, and how many have ever opened it — and it is a
   serverless function because the answer cannot live in the reader's
   own browser: a count that only one browser can see is not a count.

   Storage is Upstash Redis over its REST API, called with fetch and no
   client library. That is the same choice the carousel made about
   WebGL: the whole surface used here is one POST and one JSON
   envelope, and a dependency for that is a dependency to keep in step
   with for the rest of the site's life. The database has to have
   scripting, which every Upstash Redis does — the whole tick is one
   EVAL.

   The shape of it:

     presence:active    a sorted set, member = session id, score = the
                        millisecond that session was last heard from.
                        Every request sweeps everything older than
                        --window out of it first, so "active" is a
                        window rather than a list anyone has to tidy —
                        a closed tab simply stops arguing for itself.
     presence:total     one integer, incremented once per session and
                        never again.
     presence:seen:<id> the guard that makes that "once" true. Written
                        with NX, so the second request carrying the
                        same id cannot claim the increment however many
                        times it asks. This is what a refresh loop runs
                        into.

   Nothing here identifies anybody. The session id is a random value
   the browser made up for itself and forgets when its tab closes; no
   address, no header and no fingerprint is read, stored or logged. */

/* A session is active for this long after its last heartbeat. The
   client beats every 12s (src/hooks/usePresence.js), so a session has
   to miss two beats before it drops out — one late request on a
   throttled tab is not a reader leaving. */
const WINDOW_MS = 30_000;

/* A floor under the sweep: if the site goes quiet, the last request
   leaves behind a key that expires on its own rather than a sorted set
   of ghosts waiting for a visitor to clear it. */
const ACTIVE_TTL_S = 600;

/* How long a session id is remembered as already counted. Long enough
   that a day of refreshing is one footstep, short enough that the
   guard keys cannot accumulate. */
const SEEN_TTL_S = 60 * 60 * 24;

/* The id is generated by the browser and is the only thing this
   endpoint accepts, so it is checked rather than trusted: a bounded
   alphabet and a bounded length keep anything that arrives here from
   becoming a key of someone else's choosing. */
const ID = /^[A-Za-z0-9_-]{16,64}$/;

const ACTIVE = 'presence:active';
const TOTAL = 'presence:total';
const seen = (id) => `presence:seen:${id}`;

/* Which two variables hold the credentials is not a thing this file
   is allowed to be certain about. Upstash writes one pair, the Vercel
   integration that provisions the same database has written another,
   and a marketplace connection can be given a prefix of its own at the
   moment it is made. Hard-coding a guess is how this ends up
   configured correctly and switched off anyway.

   So it is found rather than named: any variable whose name ends in
   REST_URL or REST_API_URL, holding an https:// value, whose matching
   ...TOKEN exists beside it. That covers UPSTASH_REDIS_REST_URL, it
   covers KV_REST_API_URL, and it covers whatever prefix the next
   integration decides on. The derivation is TOKEN in place of URL,
   which is also why the read-only token is never picked up by
   accident: nothing is named ..._READ_ONLY_URL.

   Ranking, when more than one is present: a genuine Upstash host wins,
   then Upstash's own naming, then Vercel's. A database this feature
   was pointed at deliberately beats one that happens to be attached.

   Values never leave the server. Nothing below returns one, logs one,
   or puts one in a response — the names are all that is ever said out
   loud, and a name is not a secret. */
const REST_URL = /REST(?:_API)?_URL$/;
/* What to name back when none of them worked out. Deliberately wider
   than the pattern above: an integration free to choose its own prefix
   is free to choose one with no "redis" in it, and the failure path is
   the one place where listing too much is better than listing too
   little. */
const REDIS_ISH = /(?:UPSTASH|REDIS|^KV_)|REST(?:_API)?_(?:URL|TOKEN)$/;

const host = (url) => {
    try {
        return new URL(url).host;
    } catch {
        return '';
    }
};

function candidates() {
    const env = process.env;

    return Object.keys(env)
        .filter((key) => REST_URL.test(key))
        .map((urlKey) => ({
            urlKey,
            tokenKey: urlKey.replace(/URL$/, 'TOKEN'),
            url: (env[urlKey] || '').trim(),
        }))
        .filter((c) => /^https?:\/\//i.test(c.url) && (env[c.tokenKey] || '').trim())
        .map((c) => ({
            ...c,
            token: env[c.tokenKey].trim(),
            rank: (/\.upstash\.io$/i.test(host(c.url)) ? 4 : 0)
                + (c.urlKey.startsWith('UPSTASH_') ? 2 : 0)
                + (c.urlKey.startsWith('KV_') ? 1 : 0),
        }))
        .sort((a, b) => b.rank - a.rank);
}

function credentials() {
    const [best] = candidates();
    if (!best) return null;
    return { url: best.url.replace(/\/+$/, ''), token: best.token, from: best.urlKey };
}

/* What to say when there are none, and the only reason this function
   exists: an endpoint that answers "not configured" and stops has told
   whoever is setting it up nothing they did not already know. This
   lists the names it looked for and the names it can actually see, so
   the gap between them is the answer.

   Names only. Never a value, never a fragment of one, not even a
   length. */
function diagnosis() {
    const present = Object.keys(process.env).filter((key) => REDIS_ISH.test(key)).sort();

    return {
        error: 'presence store not configured',
        detail: present.length
            ? 'Redis variables are set, but no REST url/token pair was found among them. '
                + 'The REST API needs a pair named <PREFIX>_REST_URL and <PREFIX>_REST_TOKEN '
                + '(or _REST_API_URL / _REST_API_TOKEN). A redis:// or rediss:// url alone is '
                + 'the TCP endpoint, which this function does not speak.'
            : 'No Redis environment variables are visible to this function at all. If the '
                + 'database was connected after the current deployment was built, redeploy — '
                + 'Vercel does not hand new variables to an existing build.',
        looked_for: ['<PREFIX>_REST_URL + <PREFIX>_REST_TOKEN', '<PREFIX>_REST_API_URL + <PREFIX>_REST_API_TOKEN'],
        found: present,
    };
}

/* Sweep and read, without claiming anything. The health check below is
   the whole of its use: a url someone can open in a browser and be
   told what is wrong, which is a great deal easier than composing a
   POST by hand. */
const READ = `
redis.call('ZREMRANGEBYSCORE', KEYS[1], '-inf', ARGV[1])
return { redis.call('ZCARD', KEYS[1]), tonumber(redis.call('GET', KEYS[2])) or 0 }
`;

/* One HTTP round trip, one billed command, one atomic step.

   The obvious shape for this is a pipeline of six — sweep, refresh,
   bound, count, claim, read — and it was one, briefly. Three things
   sent it here instead. Upstash bills per command rather than per
   request, so six of them five times a minute is a hundred and eighty
   an hour for one open tab, which is a free database spent on one
   reader. Whether a session is new is decided by SET ... NX, and
   branching on that answer costs a pipeline a second round trip that a
   script does not pay. And a pipeline is explicitly not atomic, so the
   total could in principle be read a moment before its own increment
   lands.

   Everything the script needs is handed to it already formatted.
   Redis's Lua is 5.1 and every number in it is a double, so a
   millisecond timestamp built by concatenation there would be a
   formatting question; built here it is just a string. The script does
   no arithmetic at all.

   `redis.call('SET', ..., 'NX', ...)` answers false when the key was
   already there, which is the whole of the guard: a session that has
   been counted cannot be counted again, however many times it asks,
   and a reload asks with the same id. */
const TICK = `
redis.call('ZREMRANGEBYSCORE', KEYS[1], '-inf', ARGV[2])
redis.call('ZADD', KEYS[1], 'GT', ARGV[1], ARGV[3])
redis.call('EXPIRE', KEYS[1], ARGV[4])
local total
if redis.call('SET', KEYS[3], '1', 'NX', 'EX', ARGV[5]) then
  total = redis.call('INCR', KEYS[2])
else
  total = tonumber(redis.call('GET', KEYS[2])) or 0
end
return { redis.call('ZCARD', KEYS[1]), total }
`;

/* Upstash answers a single command with {result} or {error} — and an
   error inside a 200, which is the part that is easy to miss. */
async function command(creds, argv) {
    const res = await fetch(creds.url, {
        method: 'POST',
        headers: {
            authorization: `Bearer ${creds.token}`,
            'content-type': 'application/json',
        },
        body: JSON.stringify(argv),
        /* A footer detail is not worth a hung function. */
        signal: AbortSignal.timeout(4000),
    });

    const body = await res.json().catch(() => null);

    if (!res.ok) throw new Error(`upstash ${res.status}: ${(body && body.error) || 'no body'}`);
    if (!body || body.error) throw new Error(`upstash: ${(body && body.error) || 'unexpected reply'}`);

    return body.result;
}

export async function counts(creds, now) {
    const reply = await command(creds, [
        'EVAL', READ, 2, ACTIVE, TOTAL, `(${now - WINDOW_MS}`,
    ]);

    const [active, total] = Array.isArray(reply) ? reply : [];
    return { active: Number(active) || 0, total: Number(total) || 0 };
}

export async function tick(creds, id, now) {
    const reply = await command(creds, [
        'EVAL', TICK, 3,
        ACTIVE, TOTAL, seen(id),
        String(now),
        /* Exclusive, so a session whose last beat is exactly at the
           edge of the window is kept rather than swept. */
        `(${now - WINDOW_MS}`,
        id,
        String(ACTIVE_TTL_S),
        String(SEEN_TTL_S),
    ]);

    const [active, total] = Array.isArray(reply) ? reply : [];
    return { active: Number(active) || 0, total: Number(total) || 0 };
}

/* Vercel parses a JSON body into an object before the handler runs.
   Nothing else is promised — a different host, or the local harness
   this was tested against, hands over a string or an unread stream —
   so all three are accepted and the stream is read with a ceiling on
   it. The body is two short fields; anything larger is not one. */
async function readBody(req) {
    if (req.body && typeof req.body === 'object') return req.body;
    if (typeof req.body === 'string') {
        try { return JSON.parse(req.body); } catch { return null; }
    }

    let raw = '';
    for await (const chunk of req) {
        raw += chunk;
        if (raw.length > 2048) return null;
    }
    try { return JSON.parse(raw); } catch { return null; }
}

/* Same origin needs no headers at all. The variable exists for the one
   arrangement that does: the pages served from somewhere else — GitHub
   Pages, as they are today — and this function on Vercel. It names a
   single origin rather than allowing any. */
function cors(req, res) {
    const allowed = process.env.PRESENCE_ALLOWED_ORIGIN;
    if (!allowed) return;

    const origin = req.headers.origin;
    if (origin && origin === allowed) {
        res.setHeader('Access-Control-Allow-Origin', allowed);
        res.setHeader('Vary', 'Origin');
    }
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'content-type');
    res.setHeader('Access-Control-Max-Age', '86400');
}

export default async function handler(req, res) {
    cors(req, res);
    res.setHeader('Cache-Control', 'no-store');

    if (req.method === 'OPTIONS') {
        res.status(204).end();
        return;
    }

    if (req.method !== 'POST' && req.method !== 'GET') {
        res.setHeader('Allow', 'GET, POST, OPTIONS');
        res.status(405).json({ error: 'method not allowed' });
        return;
    }

    const creds = credentials();

    if (!creds) {
        /* Unconfigured is not broken: the footer asks once, is told
           there is nothing to show, and stays as it was. What is new
           is that it is told WHY, and so is anyone who opens this url
           — see diagnosis(). */
        res.status(503).json(diagnosis());
        return;
    }

    /* GET is the health check. It registers nobody and claims nothing;
       it sweeps, reads the two numbers the footer would have shown,
       and names the variable it took its credentials from — the name,
       not the value. Open it in a browser and it says either that the
       store is answering, or exactly what is missing. */
    if (req.method === 'GET') {
        try {
            res.status(200).json({
                ok: true,
                store: `reachable via ${creds.from}`,
                ...(await counts(creds, Date.now())),
            });
        } catch (error) {
            const detail = error && error.message ? error.message : String(error);
            console.error('presence:', detail);
            res.status(502).json({
                ok: false,
                error: 'presence store unavailable',
                /* The credentials are named and the failure is quoted,
                   because "unavailable" on its own cannot tell a wrong
                   token from a deleted database. Upstash's own replies
                   carry no secret — they are status lines. */
                store: `configured from ${creds.from}`,
                detail,
            });
        }
        return;
    }

    const body = await readBody(req);
    const id = body && typeof body.id === 'string' ? body.id : '';

    if (!ID.test(id)) {
        res.status(400).json({ error: 'invalid session id' });
        return;
    }

    try {
        /* The clock is the server's. A visitor whose own clock is
           wrong, or who would like to be counted for the next hour,
           has no say in when their session expires. */
        const now = Date.now();
        res.status(200).json(await tick(creds, id, now));
    } catch (error) {
        const detail = error && error.message ? error.message : String(error);
        console.error('presence:', detail);
        res.status(502).json({ error: 'presence store unavailable', detail });
    }
}
