/* The one piece of this site that is not a static file.
   ------------------------------------------------------------------
   It answers a single question — how many people are reading the
   portfolio right now, and how many have ever opened it — and it is a
   serverless function because the answer cannot live in the reader's
   own browser: a count that only one browser can see is not a count.

   Storage is Upstash Redis over its REST API, called with fetch and no
   client library. That is the same choice the carousel made about
   WebGL: the whole surface used here is one POST and one JSON
   envelope, and a dependency for that is a dependency to keep in step
   with for the rest of the site's life. The database has to have
   scripting, which every Upstash Redis does — the whole tick is one
   EVAL.

   The shape of it:

     presence:active    a sorted set, member = session id, score = the
                        millisecond that session was last heard from.
                        Every request sweeps everything older than
                        --window out of it first, so "active" is a
                        window rather than a list anyone has to tidy —
                        a closed tab simply stops arguing for itself.
     presence:total     one integer, incremented once per session and
                        never again.
     presence:seen:<id> the guard that makes that "once" true. Written
                        with NX, so the second request carrying the
                        same id cannot claim the increment however many
                        times it asks. This is what a refresh loop runs
                        into.

   Nothing here identifies anybody. The session id is a random value
   the browser made up for itself and forgets when its tab closes; no
   address, no header and no fingerprint is read, stored or logged. */

/* A session is active for this long after its last heartbeat. The
   client beats every 12s (src/hooks/usePresence.js), so a session has
   to miss two beats before it drops out — one late request on a
   throttled tab is not a reader leaving. */
const WINDOW_MS = 30_000;

/* A floor under the sweep: if the site goes quiet, the last request
   leaves behind a key that expires on its own rather than a sorted set
   of ghosts waiting for a visitor to clear it. */
const ACTIVE_TTL_S = 600;

/* How long a session id is remembered as already counted. Long enough
   that a day of refreshing is one footstep, short enough that the
   guard keys cannot accumulate. */
const SEEN_TTL_S = 60 * 60 * 24;

/* The id is generated by the browser and is the only thing this
   endpoint accepts, so it is checked rather than trusted: a bounded
   alphabet and a bounded length keep anything that arrives here from
   becoming a key of someone else's choosing. */
const ID = /^[A-Za-z0-9_-]{16,64}$/;

const ACTIVE = 'presence:active';
const TOTAL = 'presence:total';
const seen = (id) => `presence:seen:${id}`;

/* Upstash's own names first; the pair Vercel's marketplace integration
   writes for a Redis store second. Either is enough, and neither ever
   reaches the browser — this file runs on the server, and nothing it
   returns carries them. */
function credentials() {
    const url = process.env.UPSTASH_REDIS_REST_URL || process.env.KV_REST_API_URL;
    const token = process.env.UPSTASH_REDIS_REST_TOKEN || process.env.KV_REST_API_TOKEN;
    if (!url || !token) return null;
    return { url: url.replace(/\/+$/, ''), token };
}

/* One HTTP round trip, one billed command, one atomic step.

   The obvious shape for this is a pipeline of six — sweep, refresh,
   bound, count, claim, read — and it was one, briefly. Three things
   sent it here instead. Upstash bills per command rather than per
   request, so six of them five times a minute is a hundred and eighty
   an hour for one open tab, which is a free database spent on one
   reader. Whether a session is new is decided by SET ... NX, and
   branching on that answer costs a pipeline a second round trip that a
   script does not pay. And a pipeline is explicitly not atomic, so the
   total could in principle be read a moment before its own increment
   lands.

   Everything the script needs is handed to it already formatted.
   Redis's Lua is 5.1 and every number in it is a double, so a
   millisecond timestamp built by concatenation there would be a
   formatting question; built here it is just a string. The script does
   no arithmetic at all.

   `redis.call('SET', ..., 'NX', ...)` answers false when the key was
   already there, which is the whole of the guard: a session that has
   been counted cannot be counted again, however many times it asks,
   and a reload asks with the same id. */
const TICK = `
redis.call('ZREMRANGEBYSCORE', KEYS[1], '-inf', ARGV[2])
redis.call('ZADD', KEYS[1], 'GT', ARGV[1], ARGV[3])
redis.call('EXPIRE', KEYS[1], ARGV[4])
local total
if redis.call('SET', KEYS[3], '1', 'NX', 'EX', ARGV[5]) then
  total = redis.call('INCR', KEYS[2])
else
  total = tonumber(redis.call('GET', KEYS[2])) or 0
end
return { redis.call('ZCARD', KEYS[1]), total }
`;

/* Upstash answers a single command with {result} or {error} — and an
   error inside a 200, which is the part that is easy to miss. */
async function command(creds, argv) {
    const res = await fetch(creds.url, {
        method: 'POST',
        headers: {
            authorization: `Bearer ${creds.token}`,
            'content-type': 'application/json',
        },
        body: JSON.stringify(argv),
        /* A footer detail is not worth a hung function. */
        signal: AbortSignal.timeout(4000),
    });

    const body = await res.json().catch(() => null);

    if (!res.ok) throw new Error(`upstash ${res.status}: ${(body && body.error) || 'no body'}`);
    if (!body || body.error) throw new Error(`upstash: ${(body && body.error) || 'unexpected reply'}`);

    return body.result;
}

export async function tick(creds, id, now) {
    const reply = await command(creds, [
        'EVAL', TICK, 3,
        ACTIVE, TOTAL, seen(id),
        String(now),
        /* Exclusive, so a session whose last beat is exactly at the
           edge of the window is kept rather than swept. */
        `(${now - WINDOW_MS}`,
        id,
        String(ACTIVE_TTL_S),
        String(SEEN_TTL_S),
    ]);

    const [active, total] = Array.isArray(reply) ? reply : [];
    return { active: Number(active) || 0, total: Number(total) || 0 };
}

/* Vercel parses a JSON body into an object before the handler runs.
   Nothing else is promised — a different host, or the local harness
   this was tested against, hands over a string or an unread stream —
   so all three are accepted and the stream is read with a ceiling on
   it. The body is two short fields; anything larger is not one. */
async function readBody(req) {
    if (req.body && typeof req.body === 'object') return req.body;
    if (typeof req.body === 'string') {
        try { return JSON.parse(req.body); } catch { return null; }
    }

    let raw = '';
    for await (const chunk of req) {
        raw += chunk;
        if (raw.length > 2048) return null;
    }
    try { return JSON.parse(raw); } catch { return null; }
}

/* Same origin needs no headers at all. The variable exists for the one
   arrangement that does: the pages served from somewhere else — GitHub
   Pages, as they are today — and this function on Vercel. It names a
   single origin rather than allowing any. */
function cors(req, res) {
    const allowed = process.env.PRESENCE_ALLOWED_ORIGIN;
    if (!allowed) return;

    const origin = req.headers.origin;
    if (origin && origin === allowed) {
        res.setHeader('Access-Control-Allow-Origin', allowed);
        res.setHeader('Vary', 'Origin');
    }
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'content-type');
    res.setHeader('Access-Control-Max-Age', '86400');
}

export default async function handler(req, res) {
    cors(req, res);
    res.setHeader('Cache-Control', 'no-store');

    if (req.method === 'OPTIONS') {
        res.status(204).end();
        return;
    }

    if (req.method !== 'POST') {
        res.setHeader('Allow', 'POST, OPTIONS');
        res.status(405).json({ error: 'method not allowed' });
        return;
    }

    const creds = credentials();
    if (!creds) {
        /* Unconfigured is not broken: the footer asks once, is told
           there is nothing to show, and stays as it was. */
        res.status(503).json({ error: 'presence store not configured' });
        return;
    }

    const body = await readBody(req);
    const id = body && typeof body.id === 'string' ? body.id : '';

    if (!ID.test(id)) {
        res.status(400).json({ error: 'invalid session id' });
        return;
    }

    try {
        /* The clock is the server's. A visitor whose own clock is
           wrong, or who would like to be counted for the next hour,
           has no say in when their session expires. */
        const now = Date.now();
        res.status(200).json(await tick(creds, id, now));
    } catch (error) {
        console.error('presence:', error && error.message ? error.message : error);
        res.status(502).json({ error: 'presence store unavailable' });
    }
}
